/*
**	$Id$
**	Generated by IDLTool 53.35
**	Do not edit
**
**	AutoInit stub for euae_blit
**
**	Copyright (c) 2010 Hyperion Entertainment CVBA.
**	All Rights Reserved.
*/

#include <exec/types.h>
#include <exec/interrupts.h>
#include <exec/libraries.h>

#include <interfaces/euae_blit.h>
#include <proto/exec.h>
#include <proto/dos.h>
#include <stdlib.h>

/****************************************************************************/

struct Library * euae_blitBase = NULL;
static struct Library * __euae_blitBase = NULL;

/****************************************************************************/

void _INIT_5_euae_blitBase(void)
{
    if (euae_blitBase != NULL)
    {
        return; /* Someone was quicker, e.g. an interface constructor */
    }
    __euae_blitBase = euae_blitBase = IExec->OpenLibrary("euae-blit.library", 0);
    if (euae_blitBase == NULL)
    {
        BPTR StdErr = IDOS->ErrorOutput();
        if (StdErr == ZERO)
            StdErr = IDOS->Output();
        IDOS->FPrintf(StdErr, "ERROR: Failed to open '%s'.\n", "euae-blit.library");
        abort();
    }
}

#ifdef __GNUC__
__attribute__((section(".ctors.zzzz"))) static void
(*euae_blit_base_constructor_ptr)(void) USED = _INIT_5_euae_blitBase;
#endif

/****************************************************************************/

void _EXIT_5_euae_blitBase(void)
{
    if (__euae_blitBase != NULL)
    {
        IExec->CloseLibrary(__euae_blitBase);
    }
}

#ifdef __GNUC__
__attribute__((section(".dtors.zzzz"))) static void
(*euae_blit_base_destructor_ptr)(void) USED = _EXIT_5_euae_blitBase;
#endif

/****************************************************************************/

