/*
**	$Id$
**	Generated by IDLTool 53.35
**	Do not edit
**
**	AutoInit stub for euae_blit
**
**	Copyright (c) 2010 Hyperion Entertainment CVBA.
**	All Rights Reserved.
*/

#include <exec/types.h>
#include <exec/interrupts.h>
#include <exec/libraries.h>

#include <interfaces/euae_blit.h>
#include <proto/exec.h>
#include <proto/dos.h>
#include <stdlib.h>

struct euae_blitIFace * Ieuae_blit = NULL;
static struct Library * __euae_blitBase = NULL;
static struct euae_blitIFace * __Ieuae_blit = NULL;

/****************************************************************************/

extern struct Library * euae_blitBase;

/****************************************************************************/

void _INIT_5_Ieuae_blit(void)
{
    if (Ieuae_blit != NULL)
    {
        return; /* Someone was quicker */
    }
    if (euae_blitBase == NULL) /* Library base is NULL, we need to open it */
    {
        /* We were called before the base constructor.
         * This means we will be called _after_ the base destructor.
         * So we cant drop the interface _after_ closing the last library base,
         * we just open the library here which ensures that.
         */
        __euae_blitBase = euae_blitBase = IExec->OpenLibrary("euae-blit.library", 0);
        if (euae_blitBase == NULL)
        {
            BPTR StdErr = IDOS->ErrorOutput();
            if (StdErr == ZERO)
                StdErr = IDOS->Output();
            IDOS->FPrintf(StdErr, "ERROR: Failed to open '%s'.\n", "euae-blit.library");
            abort();
        }
    }

    __Ieuae_blit = Ieuae_blit = (struct euae_blitIFace *)IExec->GetInterface((struct Library *)euae_blitBase, "main", 1, NULL);
    if (Ieuae_blit == NULL)
    {
        BPTR StdErr = IDOS->ErrorOutput();
        if (StdErr == ZERO)
            StdErr = IDOS->Output();
        IDOS->FPrintf(StdErr, "ERROR: Failed to get '%s' V%ld interface for '%s'.\n", "main", 1, "euae-blit.library");
        abort();
    }
}
#ifdef __GNUC__
__attribute__((section(".ctors.zzzy"))) static void
(*euae_blit_main_constructor_ptr)(void) USED = _INIT_5_Ieuae_blit;
#endif

/****************************************************************************/

void _EXIT_5_Ieuae_blit(void)
{
    if (__Ieuae_blit)
    {
        IExec->DropInterface ((struct Interface *)__Ieuae_blit);
    }
    if (__euae_blitBase)
    {
        IExec->CloseLibrary(__euae_blitBase);
    }
}
#ifdef __GNUC__
__attribute__((section(".dtors.zzzy"))) static void
(*euae_blit_main_destructor_ptr)(void) USED = _EXIT_5_Ieuae_blit;
#endif

/****************************************************************************/

