
/* This file was generated by idltool 53.35. Do not edit */

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif
#ifndef EXEC_INTERRUPTS_H
#include <exec/interrupts.h>
#endif
#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif

/* forward declaration */
struct uaeblitIFace;

extern ULONG                VARARGS68K _uaeblit_Obtain(struct uaeblitIFace *);
extern ULONG                VARARGS68K _uaeblit_Release(struct uaeblitIFace *);
extern void                 VARARGS68K _uaeblit_BLTADAT(struct uaeblitIFace *, struct Custom * custom);
extern void                 VARARGS68K _uaeblit_BLTBDAT(struct uaeblitIFace *, struct Custom * custom);
extern void                 VARARGS68K _uaeblit_BLTCDAT(struct uaeblitIFace *, struct Custom * custom);
extern void                 VARARGS68K _uaeblit_BLTAMOD(struct uaeblitIFace *, struct Custom * custom);
extern void                 VARARGS68K _uaeblit_BLTBMOD(struct uaeblitIFace *, struct Custom * custom);
extern void                 VARARGS68K _uaeblit_BLTCMOD(struct uaeblitIFace *, struct Custom * custom);
extern void                 VARARGS68K _uaeblit_BLTDMOD(struct uaeblitIFace *, struct Custom * custom);
extern void                 VARARGS68K _uaeblit_BLTCON0(struct uaeblitIFace *, struct Custom * custom);
extern void                 VARARGS68K _uaeblit_BLTCON0L(struct uaeblitIFace *, struct Custom * custom);
extern void                 VARARGS68K _uaeblit_BLTCON1(struct uaeblitIFace *, struct Custom * custom);
extern void                 VARARGS68K _uaeblit_BLTAFWM(struct uaeblitIFace *, struct Custom * custom);
extern void                 VARARGS68K _uaeblit_BLTALWM(struct uaeblitIFace *, struct Custom * custom);
extern void                 VARARGS68K _uaeblit_BLTAPTH(struct uaeblitIFace *, struct Custom * custom);
extern void                 VARARGS68K _uaeblit_BLTAPTL(struct uaeblitIFace *, struct Custom * custom);
extern void                 VARARGS68K _uaeblit_BLTBPTH(struct uaeblitIFace *, struct Custom * custom);
extern void                 VARARGS68K _uaeblit_BLTBPTL(struct uaeblitIFace *, struct Custom * custom);
extern void                 VARARGS68K _uaeblit_BLTCPTH(struct uaeblitIFace *, struct Custom * custom);
extern void                 VARARGS68K _uaeblit_BLTCPTL(struct uaeblitIFace *, struct Custom * custom);
extern void                 VARARGS68K _uaeblit_BLTDPTH(struct uaeblitIFace *, struct Custom * custom);
extern void                 VARARGS68K _uaeblit_BLTDPTL(struct uaeblitIFace *, struct Custom * custom);
extern void                 VARARGS68K _uaeblit_BLTSIZE(struct uaeblitIFace *, struct Custom * custom);
extern void                 VARARGS68K _uaeblit_BLTSIZV(struct uaeblitIFace *, struct Custom * custom);
extern void                 VARARGS68K _uaeblit_BLTSIZH(struct uaeblitIFace *, struct Custom * custom);
