#ifndef UAEBLIT_INTERFACE_DEF_H
#define UAEBLIT_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 53.35.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef EXEC_INTERRUPTS_H
#include <exec/interrupts.h>
#endif
#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif

#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif

struct uaeblitIFace
{
	struct InterfaceData Data;

	APICALL ULONG (*Obtain)(struct uaeblitIFace *Self);
	APICALL ULONG (*Release)(struct uaeblitIFace *Self);
	APTR Expunge_UNIMPLEMENTED;
	APTR Clone_UNIMPLEMENTED;
	APICALL void (*BLTADAT)(struct uaeblitIFace *Self, struct Custom * custom);
	APICALL void (*BLTBDAT)(struct uaeblitIFace *Self, struct Custom * custom);
	APICALL void (*BLTCDAT)(struct uaeblitIFace *Self, struct Custom * custom);
	APICALL void (*BLTAMOD)(struct uaeblitIFace *Self, struct Custom * custom);
	APICALL void (*BLTBMOD)(struct uaeblitIFace *Self, struct Custom * custom);
	APICALL void (*BLTCMOD)(struct uaeblitIFace *Self, struct Custom * custom);
	APICALL void (*BLTDMOD)(struct uaeblitIFace *Self, struct Custom * custom);
	APICALL void (*BLTCON0)(struct uaeblitIFace *Self, struct Custom * custom);
	APICALL void (*BLTCON0L)(struct uaeblitIFace *Self, struct Custom * custom);
	APICALL void (*BLTCON1)(struct uaeblitIFace *Self, struct Custom * custom);
	APICALL void (*BLTAFWM)(struct uaeblitIFace *Self, struct Custom * custom);
	APICALL void (*BLTALWM)(struct uaeblitIFace *Self, struct Custom * custom);
	APICALL void (*BLTAPTH)(struct uaeblitIFace *Self, struct Custom * custom);
	APICALL void (*BLTAPTL)(struct uaeblitIFace *Self, struct Custom * custom);
	APICALL void (*BLTBPTH)(struct uaeblitIFace *Self, struct Custom * custom);
	APICALL void (*BLTBPTL)(struct uaeblitIFace *Self, struct Custom * custom);
	APICALL void (*BLTCPTH)(struct uaeblitIFace *Self, struct Custom * custom);
	APICALL void (*BLTCPTL)(struct uaeblitIFace *Self, struct Custom * custom);
	APICALL void (*BLTDPTH)(struct uaeblitIFace *Self, struct Custom * custom);
	APICALL void (*BLTDPTL)(struct uaeblitIFace *Self, struct Custom * custom);
	APICALL void (*BLTSIZE)(struct uaeblitIFace *Self, struct Custom * custom);
	APICALL void (*BLTSIZV)(struct uaeblitIFace *Self, struct Custom * custom);
	APICALL void (*BLTSIZH)(struct uaeblitIFace *Self, struct Custom * custom);
};

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif

#endif /* UAEBLIT_INTERFACE_DEF_H */
