
/* This file was generated by idltool 53.35. Do not edit */

#include "uaeblit_vectors.h"

STATIC uint32 VARARGS68K _uaeblit_UNIMPLEMENTED(struct uaeblitIFace *iface UNUSED)
{
  return 0;
}
STATIC CONST APTR main_v1_vectors[] =
{
    _uaeblit_Obtain,
    _uaeblit_Release,
    _uaeblit_UNIMPLEMENTED, /* Expunge */
    _uaeblit_UNIMPLEMENTED, /* Clone */
    _uaeblit_BLTADAT,
    _uaeblit_BLTBDAT,
    _uaeblit_BLTCDAT,
    _uaeblit_BLTAMOD,
    _uaeblit_BLTBMOD,
    _uaeblit_BLTCMOD,
    _uaeblit_BLTDMOD,
    _uaeblit_BLTCON0,
    _uaeblit_BLTCON0L,
    _uaeblit_BLTCON1,
    _uaeblit_BLTAFWM,
    _uaeblit_BLTALWM,
    _uaeblit_BLTAPTH,
    _uaeblit_BLTAPTL,
    _uaeblit_BLTBPTH,
    _uaeblit_BLTBPTL,
    _uaeblit_BLTCPTH,
    _uaeblit_BLTCPTL,
    _uaeblit_BLTDPTH,
    _uaeblit_BLTDPTL,
    _uaeblit_BLTSIZE,
    _uaeblit_BLTSIZV,
    _uaeblit_BLTSIZH,
    (APTR)-1
};
