#ifndef INLINE4_UAEBLIT_H
#define INLINE4_UAEBLIT_H

/*
** This file was auto generated by idltool 53.35.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef EXEC_INTERRUPTS_H
#include <exec/interrupts.h>
#endif
#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif
#include <interfaces/uaeblit.h>

/* Inline macros for Interface "main" */
#define BLTADAT(custom) Iuaeblit->BLTADAT((custom))
#define BLTBDAT(custom) Iuaeblit->BLTBDAT((custom))
#define BLTCDAT(custom) Iuaeblit->BLTCDAT((custom))
#define BLTAMOD(custom) Iuaeblit->BLTAMOD((custom))
#define BLTBMOD(custom) Iuaeblit->BLTBMOD((custom))
#define BLTCMOD(custom) Iuaeblit->BLTCMOD((custom))
#define BLTDMOD(custom) Iuaeblit->BLTDMOD((custom))
#define BLTCON0(custom) Iuaeblit->BLTCON0((custom))
#define BLTCON0L(custom) Iuaeblit->BLTCON0L((custom))
#define BLTCON1(custom) Iuaeblit->BLTCON1((custom))
#define BLTAFWM(custom) Iuaeblit->BLTAFWM((custom))
#define BLTALWM(custom) Iuaeblit->BLTALWM((custom))
#define BLTAPTH(custom) Iuaeblit->BLTAPTH((custom))
#define BLTAPTL(custom) Iuaeblit->BLTAPTL((custom))
#define BLTBPTH(custom) Iuaeblit->BLTBPTH((custom))
#define BLTBPTL(custom) Iuaeblit->BLTBPTL((custom))
#define BLTCPTH(custom) Iuaeblit->BLTCPTH((custom))
#define BLTCPTL(custom) Iuaeblit->BLTCPTL((custom))
#define BLTDPTH(custom) Iuaeblit->BLTDPTH((custom))
#define BLTDPTL(custom) Iuaeblit->BLTDPTL((custom))
#define BLTSIZE(custom) Iuaeblit->BLTSIZE((custom))
#define BLTSIZV(custom) Iuaeblit->BLTSIZV((custom))
#define BLTSIZH(custom) Iuaeblit->BLTSIZH((custom))

#endif /* INLINE4_UAEBLIT_H */
